# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectslist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='other',
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('RED', 'red'), ('WHITE', 'white'), ('BLUE', 'blue')], default='RED', max_length=5),
        ),
    ]
