# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectslist', '0002_auto_20180807_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('N', 'New'), ('R', 'In implementation'), ('D', 'Done')], default='RED', max_length=1),
        ),
        migrations.RemoveField(
            model_name='project',
            name='designerList',
        ),
        migrations.DeleteModel(
            name='DesignerList',
        ),
        migrations.AddField(
            model_name='project',
            name='designerList',
            field=models.ManyToManyField(to='projectslist.Designer'),
        ),
    ]
