# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectslist', '0003_auto_20180807_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('R', 'In implementation'), ('D', 'Done')], default='N', max_length=1),
        ),
    ]
